spring:
  session:
    store-type: none
server:
    port: 8089
dataSource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?allowMultiQueries=true&autoReconnect=true
    username: root
    password: root